services:
  - type: web
    name: beatnet-beatthis-detector
    env: python
    plan: free
    pythonVersion: "3.9.16"
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    apt:
      packages:
        - ffmpeg
        - libsndfile1
        - build-essential
        - python3-dev
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
